services:
  db:
    container_name: workoutDB
    image: postgres:18
    volumes:
      - ./database/postgres-data:/var/lib/postgresql
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
